name: YAPF Formatting Check
on:
  pull_request:
  push:
    branches:
      - master


jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Yapf Formatter
      run: |
        python -m pip install toml yapf; yapf --verbose -ir .
        